### PR TITLE
minor typos

### PR DESCRIPTION
**Pull request by Zachary-Muscavitch**

### CODE REVIEW

**Comment by kholsinger** [comment]
Zach, There's no need to make typo corrections in the book version of the notes. Any typos that are corrected in the "main" version of the notes will be automatically carried through to the book version at the end of the semester. I have a short Perl script that pulls the LaTeX files from the main directory and gets them in the right version for the book.

Thanks for catching typos.

**Comment by uconneeb** [comment]
Thanks Kent, I was making typo corrections in both places like Zach. Should have known that, of course, you'd have a script for that!

**Comment by plewis** [comment]
Sorry, that was Paul speaking. Forgot that I last signed in as uconneeb.

**Comment by Zachary-Muscavitch** [comment]
Okay, sounds good.

**Pull request merged**
